### ISSUE TITLE
Parameterized tests, parameterized suites (parameters for tests)

### ISSUE THREAD

**Issue by killoctal** [unittest-cpp/unittest-cpp#125]
As discussed in the pull request [#124](https://github.com/unittest-cpp/unittest-cpp/pull/124), I proposed my implementation of parameterized tests but the PR was rejected. This means I have to improve ;)

For me the usage is really simple and convenient, you have some examples in the [tests file](https://github.com/killoctal/unittest-cpp/blob/17d6e82ca66db64d4c93e465c7f631d6c47e27aa/tests/TestParameterizedTest.cpp) but everyone has it own point of view so please feel free to make suggestions or give ideas to make it better.

The goal is to make the feature to be accepted :)

**Comment by pjohnmeyer** [comment]
The first things I would like to understand are:

* What precisely is meant by "parameterized tests"?
* What is the use case for this feature?

I think I understand but I had a hard time figuring it out from the tests, so let me see if I have it right. The goal is to have the ability for:

* The same test to run on multiple data sets, or
* The same suite to run against multiple data sets

Is this correct?

Once I understand this, it will be easier to reason about.

**Comment by killoctal** [comment]
You are right, for me it is too clear but I did not explained it well.

The goal is to be able to execute the same test with different values, from one or several user defined data sets. I call these data sets **parameter for test**. There is no relation with suites, they are usable only inside tests which use a parameter.

The execution behavior is only changed for the tests that use one (or several) parameter, they will be executed one time with each of its value. If several are used, the test will be executed for each combinaison.

Here is a use case :
```
// File: MyParameters.h
// Note: I recommand prefix your parameter name with "pz"
class ClientAbstract
{
	//...
	int interestingMethod(int value) { return value * 3; }
	virtual bool alwaysTrue() { return true; }
	//...
}

SET_TEST_PARAMETER(ClientAbstract*, pzClient, {
    values.push_back(new RPCClient());
    values.push_back(new JsonRestHttpClient());
});

SET_TEST_PARAMETER(int, pzCriticalValues, {
    values.push_back(INT_MIN / 3);
    values.push_back(-1000);
    values.push_back(0);
    values.push_back(1000);
    values.push_back(INT_MAX / 3);
});


// File: MyTests.cpp
TEST(InterestingMethod_WithCriticalValues_OnEachClient_GivesExpectedResult)
{
	ClientAbstract* client = pzClient();
	int value = pzCriticalValues();
	int result = client->call("interestingMethod", value);
	CHECK_EQUAL(result * 3, result);
}

TEST(AlwaysTrue_OnEachClient_IsTrue)
{
	ClientAbstract* client = pzClient();
	bool result = client->call("alwaysTrue");
	CHECK(result);
}
```

**Comment by pjohnmeyer** [comment]
## Short version
I think the concept of parameterized TESTs (or perhaps, parameterized blocks of CHECKs -- a seemingly minor but significant difference) is a sound one, as long as it can be done in a way that:

* Addresses real problems with existing methods of testing against sets of data (see below)
* Is more consistent with the "look & feel" of the rest of UnitTest++
* Relies mostly on extension, and less on modification, of the core behavior (in other words, people shouldn't pay for this feature if they don't use it)

### If you have any interest in the future of this feature please chime in on this discussion!

Perfect world scenario -- this is implemented with **no changes** to existing UnitTest++ code -- then we can decide whether to incorporate it into the core or make it externally available.

## Long version 
Okay. I think the idea here is a useful one, so let's get more concrete.

The way I've typically seen testing w/ multiple inputs done today looks something like this; I'm choosing to use fixtures with the data but it can of course just be set as a file-level global if you like (I don't):

```cpp
   class TestData
   {
   public:
      TestData()
      : evens({2,4,6})
      , odds({1,3,5})
      {}

      std::vector<int> odds;
      std::vector<int> evens;
   };

   bool is_odd(int x) { return ((x & 1) == 1); }
   bool is_positive(int x) { return (x > 0); }

   TEST_FIXTURE(TestData, OddDetection)
   {
      for (size_t idx = 0; idx < odds.size(); ++idx)
      {
         CHECK(is_odd(odds[idx]));
      }
   } 
   // ...
   // Imagine more tests re evens, etc.
   // ...
   TEST_FIXTURE(TestData, PositiveDetection)
   {
      std::vector<int> odds_and_evens = odds;
      odds_and_evens.insert(odds_and_evens.end(), evens.begin(), evens.end());
      for (size_t idx = 0; idx < odds_and_evens.size(); ++idx)
      {
         CHECK(is_positive(odds_and_evens[idx]));
      }
   } 
```

The good part about this is that it's simple C++; it's clear what the tests are doing, once they understand TEST_FIXTURE, to even a novice developer. The down-sides as I see them, at a glance, are:

1. Repeating the `TEST_FIXTURE(TestData,` part over and over is a bit obnoxious
2. Error messages aren't very good in this case.

To illustrate item 2, let's say I add the negative forms `-1, -3, and -5` to the `odds` vector without thinking about the positive test case. Now I get output like this (MSVC):

```
  C:\Users\pjohn\code\pjohnmeyer\unittest-cpp\tests\TestCheckMacros.cpp(548): error : Failure in PositiveDetection: is_
positive(odds_and_evens[idx]) [C:\Users\pjohn\code\pjohnmeyer\unittest-cpp\builds\vs2015\TestUnitTest++.vcxproj]
  C:\Users\pjohn\code\pjohnmeyer\unittest-cpp\tests\TestCheckMacros.cpp(548): error : Failure in PositiveDetection: is_
positive(odds_and_evens[idx]) [C:\Users\pjohn\code\pjohnmeyer\unittest-cpp\builds\vs2015\TestUnitTest++.vcxproj]
  C:\Users\pjohn\code\pjohnmeyer\unittest-cpp\tests\TestCheckMacros.cpp(548): error : Failure in PositiveDetection: is_
positive(odds_and_evens[idx]) [C:\Users\pjohn\code\pjohnmeyer\unittest-cpp\builds\vs2015\TestUnitTest++.vcxproj]
```

Every failure looks the same. Of course in most cases I'll know what I just changed to make something like this happen, but it won't always be so obvious. Note that an implementation of [custom messages] (https://github.com/unittest-cpp/unittest-cpp/pull/75#issuecomment-142170444) would make this less problematic, because the value under test could be streamed into the output.

So, we have a concrete reason for improvement, and a potential alternative (custom messages) to your approach. But let's look more closely at your approach.

The `SET_TEST_PARAMETER` macro you have defined doesn't "look like" other UnitTest++ macros. What does that mean?

All of the other UnitTest++ macros that take a block of code look like:

```cpp
    MACRO(parameter)
    {
       // block of code
    }
```

The block of code isn't passed as a parameter, it comes after the macro.

The `SET_TEST_PARAMETER` macro also modifies global state in a way that UT++ macros generally don't (at least without cleaning up after themselves, using RAII or the like).

Working at previous jobs, I would often "add features" to UnitTest++ by creating new macros and working from the outside in. (For example, I made a macro that let me use fixtures that required parameters in their constructor.)  I don't know if that's possible here, but that would be my approach if I were to tackle this.

Personally, I would like to see this feature take a form that looks a little bit more like a loop, since that's in essence what it is. Maybe something like this:

```cpp
   std::vector<int> odds({1,3,5});
   std::vector<int> evens({2,4,6});

   USING(value, odds) // for each value in odds
   {
      TEST(OddDetection)
      {
         CHECK(is_odd(value));
      }
      // Imagine more tests onthis data set...
   }

   std::vector<int> odds_and_evens = odds;
   USING(param, odds_and_evens)
   {
      TEST(PositiveDetection)
      {
         CHECK(is_positive(param));
      }
      // Imagine more tests on this data set...
   }       
```

I could also see the `USING` (or whatever we want to call it) directive being inside the test, around a CHECK or block of CHECKs, a la `REQUIRE`. That might be easier to implement, but would require more repetition.

I would definitely like to hear more from the community before anybody goes down any of these roads, though.

**Comment by killoctal** [comment]
Hi John,
Thank you for your review and the time taken.

# Short version
I totally understand what you are pointing to, I would ask the same questions. But everything has a reason, I forced myself to respect 2 constraints :

1. _Small and easy code usage_ (developer does not want to be annoyed with implementation details)
2. _Flexibility_ (not a single way to use, compatible with C++ < 11)

**John:** _People shouldn't pay for this feature if they don't use it_
I think the parameterized tests was (and is still) missing in UnitTest++ and it is an important lack.

# Long version
### Point 1
The parameters do not have to be global in a dedicated file, they also can be defined locally, I wrote the example that way for show it is possible. The compatibility of a local/global implementation was not that trivial, in a previous version I declared instances like `struct Foo { } fooInstance;` but depending if you declare it in *.h or *.cpp you might have several real instances instead of a single one. This is why I had to create a static instance but anyway the constructor has no effect.

### Point 2
```
std::vector<int> odds({1,3,5});
TEST(OddDetection) { ... }
...
```
Yes, I really would like to do this way but this kind of inline vector declaration is not possible before C++11. As you can see in these examples I tried to find a flexible declaration, with just a single macro. This is the reason why the macro `SET_TEST_PARAMETER` does not look like standard ones.

**If you are using C++ < 11 :**
```
SET_TEST_PARAMETER(int, odds,
{
	values.push_back(1);
	values.push_back(3);
	values.push_back(5);
});
```

**If you are using C++ >= 11**
```
SET_TEST_PARAMETER(int, odds, values = {1,3,5});

std::vector<int> evensValues({2,4,6});
SET_TEST_PARAMETER(int, evens, values = evensValues);
```

What do you think about writing 2 versions ?
```
SET_TEST_PARAMETER(int, odds, {1,3,5}); // For C++ 11 users

INIT_TEST_PARAMETER(int, odds) // For non C++11 users
{
	values.push_back(1);
	values.push_back(3);
	values.push_back(5);
}
```

### Point 3
```
USING(value, odds)
{
	TEST(OddDetection) { ... }
}
```
In Java it is common to see the parameters of test in the test header but in our case I think it not ideal :
- You still have to declare the vectors somewhere with [painful global initializations](http://stackoverflow.com/a/13899893), so it requires more code
- How do you proceed if you need multiple parameters ?
- How do you manage the tests organization in the file if you have several tests which must use several parameters but in a different manner ? (see example below)
```
USING(value, odds)
{
	USING(value2, foo)
	{
		TEST(OddDetection) { ... }
	}
}

USING(value3, bar)
{
	USING(value4, foo)
	{
		USING(value, odds)
		{
			TEST(BiduleDetection) { ... }
		}
	}
}
```
Personally I think that the only interest is that the intention of parameters usage is explicit.

The way I propose is so simple to use, if you need a new or existing parameter in a test somewhere you just have to call it by its name. Here is the same tests declaration, much simpler :
```
TEST(OddDetection)
{
	int a = odds();
	int b = foo();
}

TEST(BiduleDetection)
{
	int a = bar();
	int b = foo();
	int c = odds();
}
```

One of the other advantages is that you also can call a parameter from a function so you can cover several case even if you don't know its real implementation when you call it :
```
Message* generateFakeMessage()
{
	Message* m = new Message();
	m->set_action( pzMessageAction() ); // <- here is a parameter
	return m;
}

TEST(SerializationDeserialization_GiveSameData)
{
	Message* original = generateFakeMessage()
	char[] messageSerialized = original->serialize();
	Message* result = Message::deserialize(messageSerialized);
	CHECK_EQUAL(pzMessageAction(), result->action());
	CHECK_EQUAL(pzMessagesColors(), result->color());
}

TEST(AnyUsageTest)
{
	Message* m = generateFakeMessage();
	// Other usage of "m"
}
```

**Comment by pjohnmeyer** [comment]
_[ Trivia note: My name is Patrick; see https://github.com/pjohnmeyer ]_

**Comment by pjohnmeyer** [comment]
Let me get a few smaller points out of the way before getting to the meat of my reply in the next comment.

> > People shouldn't pay for this feature if they don't use it

I think I may have been unclear in my statement. What I meant by "paying" for a feature is in runtime and memory cost. By implementing the feature based on _extension_ over _modification_, users that don't utilize this new feature won't be adversely effected.

> ... this kind of inline vector declaration is not possible before C++11 ...

I am aware I used C++11 in my example, that was for brevity. I don't want the conversation to be bogged down by language semantics at this stage, those are implementation details that can be worried about if / when we come to conceptual agreement.

**Comment by killoctal** [comment]
Hi Patrick,

Sorry about your name, I deduced it from your pseudo.
My English level is medium so maybe I understand too literally what you meant. 

Ok I understand better what you mean about performances. Maybe we can minimize performance impact with the following idea, what do you think about it ? :)
```
// 1. Declare parameter(s)
SET_TEST_PARAMETER(int, odd, {2,4,6});
SET_TEST_PARAMETER(int, even, {1,3,5});

//2. Enable the parameterized feature with macro (no params)
PARAMETERIZED
{
    TEST(Foo)
    {
        int a = odd();
    }
    TEST(Bar)
    {
        int b = even();
    }
}

TEST(Baz)
{
    int b = even(); // Compilation error
}
```

**Comment by pjohnmeyer** [comment]
Research material from other C++ test libs for our reference:

* [Google Test - Value Parameterized Tests](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#how-to-write-value-parameterized-tests)
* [Boost Test - Data-driven test cases](http://www.boost.org/doc/libs/1_61_0/libs/test/doc/html/boost_test/tests_organization/test_cases/test_case_generation.html)
* Catch doesn't appear to have anything

**Comment by pjohnmeyer** [comment]
A few more quick answers. I'm still pondering a bit on the bigger picture, and hoping some additional community members will weigh in.

> What do you think about writing 2 versions ?

I would find that confusing.

#### Regarding the `USING` construct above
> You still have to declare the vectors somewhere with painful global initializations, so it requires more code

This is a detail we can attempt to address in the design, certainly, and something your design does address to a degree.

> How do you proceed if you need multiple parameters ?

An array etc of objects to extract the parameters from.

> How do you manage the tests organization in the file if you have several tests which must use several parameters but in a different manner ?

Good question. This is probably one reason Google Test and Boost Test support generator functions, although I can't say that for certain.

**Comment by killoctal** [comment]
> > How do you proceed if you need multiple parameters ?

> An array etc of objects to extract the parameters from.

I am not sure to understand your idea. You would put all your different parameters in an array of wrappers, like the example below ?
```
struct ParamsWrapper
{
    int odd;
    int even;
    IClient* client;
};
```
If yes, it is not multi-parameters, it is still single-parameter. To do real multi-parameters with this approach (for testing each client with each odd and each even values) you will have to explicit all combinaisons ([3 odds] * [3 even] * [2 clients] = 18 wrappers instances to write). And again, how to proceed if a test requires different combinaisons of parameters, you will have to create a new wrapper class and explicit again...

I think my proposal of [this message](https://github.com/unittest-cpp/unittest-cpp/issues/125#issuecomment-243241607) is a good compromise (I edited it a little bit).

**Comment by pjohnmeyer** [comment]
> > > How do you proceed if you need multiple parameters ?

> > An array etc of objects to extract the parameters from.

> I am not sure to understand your idea. You would put all your different parameters in an array of wrappers, like the example below? ... If yes, it is not multi-parameters, it is still single-parameter.

Not if you flatten the combinations out into a single array of `ParamsWrapper`. This can be done in advance, or using a stateful generator function if the cost of generation is too great (or the data is in a file, or...).

**Comment by pjohnmeyer** [comment]
Having thought about this and the examples above more, my three pain points stand, and I'll add a 3b from @killoctal's notes and a 4th of my own.

1. Repeating the `TEST_FIXTURE(TestData,` part over and over is a bit obnoxious
2. Error messages aren't very good in this case.
3. The odds and evens vectors are either:
    a. constructed for every test, or
    b. subject to "painful global initializations"
4. The developer has to "manually" write loops in each test

In this comment I aim to address all of these issues, having spent more time mulling over them.

Items 1 and 3a are addressed by, in cases such as this one in which the same test data is used over and over, by just not doing it that way. This leaves us with 2 and 3b.

Personally, I just don't find these "painful global initializations" that painful. To take my previous example and address this, I would do something like this:

```cpp
   namespace
   {
      const std::vector<int>& odds()
      {
         static const std::vector<int> values = {1,3,5};
         return values;
      }

      const std::vector<int>& evens()
      {
         static const std::vector<int> values = {2,4,6};
         return values;
      }
   }

   bool is_odd(int x) { return ((x & 1) == 1); }
   bool is_positive(int x) { return (x > 0); }

   TEST(OddDetection)
   {
      for (size_t idx = 0; idx < odds().size(); ++idx)
      {
         CHECK(is_odd(odds()[idx]));
      }
   } 
   // ...
   // Imagine more tests re evens, etc.
   // ...
   TEST(PositiveDetection)
   {
      for (size_t idx = 0; idx < odds().size(); ++idx)
      {
         CHECK(is_positive(odds()[idx]));
      }

      for (size_t idx = 0; idx < evens().size(); ++idx)
      {
         CHECK(is_positive(evens()[idx]));
      }
   }
```

Now yes, the developer has to write for loops to check all inputs (issue 4 above) -- but at least that's a basic skill, and it's immediately obvious what is happening to the reader.

Lets turn then to issue 2. If we create an implementation of custom messages, we can get rid of this. Imagine for a moment that you can do something like this:

```cpp
   int val_under_test = odds()[idx];
   CHECK(is_positive(val_under_test)) << " value is " << val_under_test;
```

and that in our aforementioned failure case, you now saw this:

```
  C:\Users\pjohn\code\pjohnmeyer\unittest-cpp\tests\TestCheckMacros.cpp(548): error : Failure in PositiveDetection: is_positive(val_under_test); value is -1 [C:\Users\pjohn\code\pjohnmeyer\unittest-cpp\builds\vs2015\TestUnitTest++.vcxproj]
  C:\Users\pjohn\code\pjohnmeyer\unittest-cpp\tests\TestCheckMacros.cpp(548): error : Failure in PositiveDetection: is_positive(odds_and_evens[idx]); value is -3 [C:\Users\pjohn\code\pjohnmeyer\unittest-cpp\builds\vs2015\TestUnitTest++.vcxproj]
  C:\Users\pjohn\code\pjohnmeyer\unittest-cpp\tests\TestCheckMacros.cpp(548): error : Failure in PositiveDetection: is_positive(odds_and_evens[idx]); value is -5 [C:\Users\pjohn\code\pjohnmeyer\unittest-cpp\builds\vs2015\TestUnitTest++.vcxproj]
```

Now it's incredibly clear what is happening. It's a little gross here that we're duplicating `val_under_test`, but remember this is an academic example. In a more complex example, the user can output the _most meaningful thing to them_ for that particular `CHECK` without outputting the entire parameter set. This is arguably a good duplication because it's giving the user full control of the output.

For my money, I think the bang for the buck is in supporting custom messages over parameterized testing. But, I definitely see the value of being able to wrap a set of tests without having to repeat the loops.

The thing that I just can't get past about your proposed implementation is this: it doesn't look like C++. It's a _cool_ implementation -- call these functions and you implicitly get test repetition. But "normal" C++ doesn't behave like this. Looping is explicit. Wrapping the TEST in a `PARAMETERIZED` block helps, but it still, in my opinion, hides too much.

I'm going to see if I have time to spend on an alternate prototype implementation or two to throw out there, but if somebody else wants to tackle this I'd love to see others' ideas. I'm sure somebody out there has done something like this for their project(s).

_P.S. I've decided I don't like the name `USING` because, while clearly a macro, it's the same word as the C++ keyword `using`._

**Comment by killoctal** [comment]
> It doesn't look like C++. It's a cool implementation (...) But "normal" C++ doesn't behave like this. Looping is explicit. Wrapping the TEST in a `PARAMETERIZED` block helps, but it still, in my opinion, hides too much.

So why not simply rename this macro `FOR_EACH_PARAMETER` ? If not, what do you propose ?
```
SET_TEST_PARAMETER(int, odd, {2,4,6});
SET_TEST_PARAMETER(int, even, {1,3,5});

FOR_EACH_PARAMETER
{
    TEST(Foo)
    {
        int a = odd();
    }
    TEST(Bar)
    {
        int b = even();
    }
}
```

PS: About USING, I

**Comment by pjohnmeyer** [comment]
I think this would feel more like C++ and UnitTest++ if it looked more like one of the following. I think option 1 is easier to implement (and in fact I wrote a very dumb version of it locally to test out the concept, with all of the new logic in the `TEST_EACH` macro). Option 2 of course would result in less repetition in cases where the same test data is used repeatedly, but would, I believe, be significantly harder to write.

Thanks to @bgbarcus who helped me iron some of this out the other day. He and I discussed that providing the start and end of each collection might even be desirable, but in the end I'm erring on the side of simple interface over flexible interface.

Thoughts?

### Option 1: `TEST_EACH`
```cpp
   #define TEST_EACH(CollectionExpression, Name) // impl...

   // example
   TEST_EACH(odds(), OddDetection)
   {
      CHECK(is_odd(input));
   } 
```

where:

* `CollectionExpression` is an expression that results in an STL container that supports forward iteration, a C array, or a generator object that behaves like a STL container that supports forward iteration
* `Name` is the name of the test, e.g. `OddDetection`
* `input` is the dereferenced "iterator"

Optionally the name for `input` might be another argument to the macro.

### Option 2: `WITH_EACH`

```cpp
   #define WITH_EACH(CollectionExpression) // impl...

   // example
   WITH_EACH(odds())
   {
      TEST(OddDetection)
      {
         CHECK(is_odd(input));
      }
   }
```

where:

* `CollectionExpression` is an expression that results in an STL container that supports forward iteration, a C array, or a generator object that behaves like a STL container that supports forward iteration
* `Name` is the name of the test, e.g. `OddDetection`
* `input` is the dereferenced "iterator"

Again, optionally, the name for `input` might be another argument to the macro.

**Comment by killoctal** [comment]
Use iterators is a great suggestion.

It still miss the ability of having more than 1 collection iterated in the same time. These macro `WITH_EACH` and `TEST_EACH` are still the same than :

    // I wrote C++11 for simplicity
    for(auto input : odds() )
        CHECK(is_odd(input));

But user should be able to do it but with `N` collections :

    for(auto input1 : foos() )
        for(auto input2 : odds() )
        {
            CHECK(is_odd(input2));
            CHECK(is_special(input1 * input2));
        }

Another thing, I think we should not introduce the new keyword "_with_" for specify a loop, "_for_" is more C++ like. So I propose to do use this syntax :

    FOR_EACH( odds(), foos() )
    {
        TEST(OddDetection)
        {
            CHECK(is_odd(input));
        }
    }
